name: San Thau Bang Truot

on:
  schedule:
    - cron: '0 * * * *' # Chạy tự động mỗi tiếng 1 lần
  workflow_dispatch: # Nút bấm để bạn chạy tay bất cứ lúc nào

jobs:
  run-crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Crawler
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
